import React, { useMemo, useState } from 'react';
import './GreenScore.css';
import Header from '../components/Header';
import { useHardwareMetrics, useGreenScore, useAnimatedValue } from '../hooks/useHardware';
import { Award, Download, Leaf, Cpu, Zap, TrendingUp, CheckCircle, XCircle } from 'lucide-react';

const ScoreRing: React.FC<{ score: number; size?: number; strokeW?: number; label?: string }> = ({
    score, size = 200, strokeW = 12, label
}) => {
    const r = (size / 2) - strokeW;
    const circ = 2 * Math.PI * r;
    const offset = circ - (score / 100) * circ;
    const color = score >= 80 ? 'var(--green-primary)' : score >= 60 ? 'var(--orange-accent)' : 'var(--red-accent)';

    return (
        <div className="score-ring-wrapper" style={{ width: size, height: size }}>
            <svg width={size} height={size}>
                <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="var(--border-subtle)" strokeWidth={strokeW} />
                <circle
                    cx={size / 2} cy={size / 2} r={r}
                    fill="none"
                    stroke={color}
                    strokeWidth={strokeW}
                    strokeDasharray={circ}
                    strokeDashoffset={offset}
                    strokeLinecap="round"
                    transform={`rotate(-90 ${size / 2} ${size / 2})`}
                    style={{ transition: 'stroke-dashoffset 1s var(--ease-smooth)', filter: `drop-shadow(0 0 8px ${color})` }}
                />
            </svg>
            <div className="score-ring-inner">
                <span className="score-ring-val mono" style={{ color }}>{score}</span>
                <span className="score-ring-label">{label ?? 'GREEN SCORE™'}</span>
            </div>
        </div>
    );
};

const SubScore: React.FC<{ label: string; value: number; color: string; icon: React.ReactNode }> = ({ label, value, color, icon }) => (
    <div className="sub-score-item">
        <div className="sub-score-icon" style={{ color, background: `${color}15`, border: `1px solid ${color}30` }}>{icon}</div>
        <div className="sub-score-body">
            <div className="sub-score-label">{label}</div>
            <div className="sub-score-bar">
                <div className="sub-score-fill" style={{ width: `${value}%`, background: color, boxShadow: `0 0 6px ${color}90` }} />
            </div>
        </div>
        <span className="sub-score-val mono" style={{ color }}>{Math.round(value)}</span>
    </div>
);

interface ReportData {
    score: number;
    metrics: { label: string; value: string; }[];
    checklist: { item: string; pass: boolean; }[];
}

const generateReport = (score: ReturnType<typeof useGreenScore>, power: number) => {
    const data: ReportData = {
        score: score.total,
        metrics: [
            { label: 'Overall Green Score™', value: `${score.total}/100` },
            { label: 'Power Efficiency', value: `${Math.round(score.efficiency)}/100` },
            { label: 'Carbon Impact Score', value: `${Math.round(score.carbonImpact)}/100` },
            { label: 'Hardware Utilization', value: `${Math.round(score.hardwareUtil)}/100` },
            { label: 'Optimization Level', value: `${Math.round(score.optimizationLevel)}/100` },
            { label: 'Total Power Draw', value: `${power.toFixed(1)}W` },
            { label: 'Timestamp', value: new Date().toISOString() },
            { label: 'Hardware', value: 'AMD Ryzen AI (XDNA™ 2 NPU)' },
        ],
        checklist: [
            { item: 'NPU utilized for AI inference', pass: score.optimizationLevel > 20 },
            { item: 'Cloud dependency eliminated', pass: true },
            { item: 'Sub-10W inference power envelope', pass: power < 10 },
            { item: 'Quantization applied (INT8/BF16)', pass: false },
            { item: 'Model pruning applied', pass: false },
            { item: 'AMD Ryzen AI hardware detected', pass: true },
        ],
    };
    const text = [
        '═══════════════════════════════════════',
        '        GREENLENS X — GREEN SCORE™ REPORT',
        '        AMD Slingshot AI Sustainability Platform',
        '═══════════════════════════════════════',
        '',
        `  Overall Score: ${data.score}/100`,
        '',
        '  METRICS:',
        ...data.metrics.map(m => `    ${m.label}: ${m.value}`),
        '',
        '  SUSTAINABILITY CHECKLIST:',
        ...data.checklist.map(c => `    [${c.pass ? '✓' : '✗'}] ${c.item}`),
        '',
        '  RECOMMENDATION:',
        data.score >= 80
            ? '  Excellent sustainability profile! Continue using AMD NPU for inference.'
            : '  Consider enabling INT8 quantization and routing more workloads to the NPU.',
        '',
        '═══════════════════════════════════════',
        '  Generated by GreenLens X v1.0 · AMD Slingshot',
        `  ${new Date().toLocaleString()}`,
        '═══════════════════════════════════════',
    ].join('\n');
    return { data, text };
};

const GreenScore: React.FC = () => {
    const { metrics } = useHardwareMetrics();
    const score = useGreenScore(metrics);
    const animTotal = useAnimatedValue(score.total);
    const [downloading, setDownloading] = useState(false);

    const { data: reportData, text: reportText } = useMemo(() => generateReport(score, metrics?.total_power ?? 0), [score, metrics]);

    const handleDownload = () => {
        setDownloading(true);
        const blob = new Blob([reportText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `greenlens-report-${Date.now()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        setTimeout(() => setDownloading(false), 1500);
    };

    const gradeLabel = score.total >= 90 ? 'EXCELLENT' : score.total >= 75 ? 'GOOD' : score.total >= 60 ? 'AVERAGE' : 'NEEDS WORK';
    const gradeColor = score.total >= 90 ? 'var(--green-primary)' : score.total >= 75 ? 'var(--orange-accent)' : 'var(--red-accent)';

    return (
        <div className="score-layout">
            <Header metrics={metrics} pageTitle="GREEN SCORE™" pageDesc="Sustainability rating for your AI project — downloadable for submissions" />
            <div className="score-content">

                {/* Hero */}
                <div className="score-hero-col">
                    <div className={`card score-hero-card ${score.total >= 80 ? 'glass-accent' : ''}`}>
                        <div className="card-header">
                            <span className="card-title">OVERALL SUSTAINABILITY SCORE</span>
                            <div className="award-icon"><Award size={20} className="text-green" /></div>
                        </div>
                        <div className="score-hero-body">
                            <ScoreRing score={Math.round(animTotal)} size={240} strokeW={14} />
                            <div className="score-grade" style={{ color: gradeColor }}>{gradeLabel}</div>
                            <div className="score-summary">
                                {score.total >= 80
                                    ? 'Your AI workload is running on an exemplary green path. AMD XDNA™ 2 is doing its job.'
                                    : 'Optimization opportunities available. Switch inference to NPU and enable INT8 to improve.'}
                            </div>
                            <button
                                className={`btn btn-primary download-btn ${downloading ? 'downloading' : ''}`}
                                onClick={handleDownload}
                            >
                                <Download size={16} />
                                {downloading ? 'GENERATING...' : 'DOWNLOAD REPORT'}
                            </button>
                        </div>
                    </div>
                </div>

                {/* Sub score breakdown */}
                <div className="score-breakdown-col">
                    <div className="card">
                        <div className="card-header">
                            <span className="card-title">SCORE BREAKDOWN</span>
                        </div>
                        <div className="sub-scores">
                            <SubScore label="Power Efficiency" value={score.efficiency} color="var(--blue-accent)" icon={<Zap size={14} />} />
                            <SubScore label="Carbon Impact" value={score.carbonImpact} color="var(--green-primary)" icon={<Leaf size={14} />} />
                            <SubScore label="Hardware Utilization" value={score.hardwareUtil} color="var(--orange-accent)" icon={<Cpu size={14} />} />
                            <SubScore label="Optimization Level" value={score.optimizationLevel} color="var(--purple-accent)" icon={<TrendingUp size={14} />} />
                        </div>
                    </div>

                    <div className="card">
                        <div className="card-header">
                            <span className="card-title">SUB-SCORES</span>
                        </div>
                        <div className="ring-grid">
                            <ScoreRing score={Math.round(score.efficiency)} size={100} strokeW={8} label="EFFICIENCY" />
                            <ScoreRing score={Math.round(score.carbonImpact)} size={100} strokeW={8} label="CARBON" />
                            <ScoreRing score={Math.round(score.hardwareUtil)} size={100} strokeW={8} label="HARDWARE" />
                            <ScoreRing score={Math.round(score.optimizationLevel)} size={100} strokeW={8} label="OPTIMIZED" />
                        </div>
                    </div>
                </div>

                {/* Checklist + metrics */}
                <div className="score-report-col">
                    <div className="card">
                        <div className="card-header">
                            <span className="card-title">SUSTAINABILITY CHECKLIST</span>
                        </div>
                        <div className="checklist">
                            {reportData.checklist.map((item, i) => (
                                <div key={i} className={`checklist-item ${item.pass ? 'pass' : 'fail'}`}>
                                    {item.pass ? <CheckCircle size={14} className="text-green" /> : <XCircle size={14} className="text-accent-red" />}
                                    <span>{item.item}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="card">
                        <div className="card-header">
                            <span className="card-title">REPORT METRICS</span>
                        </div>
                        <div className="report-metrics">
                            {reportData.metrics.slice(0, 6).map((m, i) => (
                                <div key={i} className="report-metric-row">
                                    <span className="report-metric-label">{m.label}</span>
                                    <span className="report-metric-val mono">{m.value}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="card recommendation-card">
                        <div className="card-header">
                            <span className="card-title">RECOMMENDATIONS</span>
                        </div>
                        <div className="recs">
                            <div className="rec-item">
                                <span className="rec-num">01</span>
                                <div>
                                    <div className="rec-title">Enable INT8 Quantization</div>
                                    <div className="rec-desc">Expected score boost: +12 pts · Power saved: ~60%</div>
                                </div>
                            </div>
                            <div className="rec-item">
                                <span className="rec-num">02</span>
                                <div>
                                    <div className="rec-title">Route all inference to AMD NPU</div>
                                    <div className="rec-desc">Expected score boost: +8 pts · Power saved: ~80%</div>
                                </div>
                            </div>
                            <div className="rec-item">
                                <span className="rec-num">03</span>
                                <div>
                                    <div className="rec-title">Enable model pruning</div>
                                    <div className="rec-desc">Expected score boost: +6 pts · Latency reduction: ~30%</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default GreenScore;
